# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true

- task: Xcode@5
  inputs:
    actions: 'build-for-testing'
    configuration: 'Debug'
    sdk: 'iphoneos'
    xcWorkspacePath: '*.xcworkspace'
    scheme: 'sampleapp-ios-swift'
    packageApp: false
    destinationDevices: 'platform=iOS Simulator,name=iPhone SE,OS=12.2'
    publishJUnitResults: true
    args: '-derivedDataPath build/derivedData'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '/usr/local/bin/appcenter test prepare xcuitest --artifacts-dir ./AppCenterTest --build-dir build/derivedData/Build/Products/Debug-iphoneos --quiet'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls ./AppCenterTest'

- task: AppCenterTest@1
  inputs:
    prepareTests: false
    appFile: 'AppCenterTest/sampleapp-ios-swiftUITests-Runner.ipa'
    frameworkOption: 'xcuitest'
    xcUITestBuildDirectory: 'build/derivedData/Build/Products/Debug-iphoneos'
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'appcenter'
    localeOption: 'en_US'
    appSlug: 'vinicyus/sampleapp'
    devices: '7259410b'
